title: Sherry Yang
tagline: Bridging AI, Genomics, and Healthcare Innovation
email: nyang19@stanford.edu
description: >-
  PhD candidate at Stanford combining machine learning with genomics to unlock 
  insights into diseases. Passionate about translating scientific 
  breakthroughs into real-world impact.

baseurl: ""
url: "https://sherry-yang.github.io"  

linkedin_username: sherry-n-yang

markdown: kramdown
